version: 1
from: "infracamp/kickstart-flavor-gaia:testing"

apache_fallback_resource: "/index.php"

command:
  build:
    - "composer update"

  test:
    - "vendor/bin/tester -C tests/"

  test_bin:
    - "cat test/_mock/demo.in.txt | bin/tbfc --tbfc --pack --stdin --stdout | bin/tbfc --tbfc --unpack --stdin --stdout"

  bench:
    - "php -f test/benchmark/file-reader-buffered.php"

