version: 1
from: "infracamp/kickstart-flavor-gaia:testing"

apache_fallback_resource: "/index.php"

command:
  build:
    - "composer update"

  test:
    - "phpunit tests/"

  test_bin:
  - "cat tests/Integration/mock/test_real_data.txt | bin/tbfc --tbfc --pack --indurad5colQuickfix --stdin --stdout > bin_out.bin"

  test_bin_dec:
    - "cat test/input.tsv | bin/tbfc --tbfc --pack --stdin --stdout | bin/tbfc --tbfc --unpack --stdin --stdout > test/out.tsv"

  bench:
    - "php -f test/benchmark/file-reader-buffered.php"


